import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import './style.css';

declare global { interface Window { __VIS_READY__?: boolean; __INTERACTION_COUNT__?: number } }
const W=1400,H=900,choice=new URLSearchParams(location.search).get('scene')??'orbital';
const canvas=document.createElement('canvas');canvas.id='stage';document.querySelector('#app')!.append(canvas);
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setSize(W,H,false);renderer.setPixelRatio(1);renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,W/H,.1,100);camera.position.set(0,1.2,10.5);
const controls=new OrbitControls(camera,canvas);controls.enableDamping=false;controls.enablePan=false;controls.minDistance=5;controls.maxDistance=18;
scene.add(new THREE.HemisphereLight(0xbfe8ff,0x101426,2.2));const key=new THREE.DirectionalLight(0xffd7a1,4);key.position.set(5,7,8);scene.add(key);const rim=new THREE.PointLight(0x6d8cff,50,20);rim.position.set(-6,2,-4);scene.add(rim);
const root=new THREE.Group();scene.add(root);
const colors=[0x54d6c6,0xffd166,0xff6f91,0x7b9cff,0xb889ff,0x62b9ff];
const material=(c:number,opacity=.86)=>new THREE.MeshStandardMaterial({color:c,metalness:.36,roughness:.28,transparent:true,opacity,side:THREE.DoubleSide});
function orbital(){
  for(let i=0;i<9;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.1+i*.29,.012+(i%3)*.008,10,180),new THREE.MeshBasicMaterial({color:colors[i%6],transparent:true,opacity:.42}));ring.rotation.x=Math.PI/2.4+i*.045;ring.rotation.y=-.35+i*.08;root.add(ring);const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.11+(i%3)*.045,1),material(colors[(i+2)%6]));const a=.72+i*.84;orb.position.set(Math.cos(a)*(1.1+i*.29),Math.sin(a)*.28,Math.sin(a)*(1.1+i*.29));root.add(orb)}
  const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.9,3),material(0xff9d66,.95));core.scale.set(1,1.12,1);root.add(core);root.rotation.x=.18;root.rotation.z=-.1;
}
function terrain(){
  const n=74,size=7.5,geo=new THREE.PlaneGeometry(size,size,n-1,n-1);const pos=geo.attributes.position;const cols=[] as number[];
  for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i),z=.52*Math.sin(x*1.5)*Math.cos(y*1.15)+.24*Math.sin((x+y)*3.1)+.13*Math.cos(Math.hypot(x,y)*5);pos.setZ(i,z);const c=new THREE.Color().setHSL(.52+.16*(z+.8)/1.6,.75,.48+.18*(z+.8)/1.6);cols.push(c.r,c.g,c.b)}geo.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));geo.computeVertexNormals();
  const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,wireframe:false,metalness:.15,roughness:.55,transparent:true,opacity:.9,side:THREE.DoubleSide}));mesh.rotation.x=-1.05;mesh.rotation.z=-.28;root.add(mesh);
  const wire=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:0xcbefff,wireframe:true,transparent:true,opacity:.12}));wire.rotation.copy(mesh.rotation);wire.position.z=.015;root.add(wire);
}
function crystal(){
  const geo=new THREE.OctahedronGeometry(.31,0);for(let i=0;i<78;i++){const mesh=new THREE.Mesh(geo,material(colors[i%6],.66));const a=i*2.399,r=.4+.052*i;mesh.position.set(Math.cos(a)*r,(i%9)*.16-0.7+Math.sin(i*.7)*.25,Math.sin(a)*r*.55);mesh.rotation.set(i*.17,i*.31,i*.11);const s=.45+(i%7)*.13;mesh.scale.set(s,1.3*s,s);root.add(mesh)}
  const halo=new THREE.Mesh(new THREE.TorusKnotGeometry(2.15,.035,180,10,3,7),new THREE.MeshBasicMaterial({color:0xa8deff,transparent:true,opacity:.34}));halo.rotation.x=1.2;root.add(halo);root.rotation.y=-.45;
}
function molecule(){const atoms=[[-2,0,0,0],[-1,.6,.2,1],[0,0,0,2],[1,.7,-.2,0],[2,0,.1,3],[0,-1.2,.5,4],[-1.8,-1.1,-.4,2],[1.8,-1.2,.3,1]] as const;const sphere=new THREE.SphereGeometry(.32,28,18);atoms.forEach(([x,y,z,c],i)=>{const a=new THREE.Mesh(sphere,material(colors[c],.9));a.position.set(x,y,z);a.scale.setScalar(1+(i%3)*.22);root.add(a);if(i){const prev=new THREE.Vector3(...atoms[i-1].slice(0,3) as [number,number,number]),next=new THREE.Vector3(x,y,z),mid=prev.clone().add(next).multiplyScalar(.5),len=prev.distanceTo(next);const bond=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,len,12),material(0xb8d8e8,.65));bond.position.copy(mid);bond.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),next.clone().sub(prev).normalize());root.add(bond)}});root.rotation.set(.4,-.4,.12)}
function city(){const geo=new THREE.BoxGeometry(.45,1,.45);for(let x=-8;x<=8;x++)for(let z=-5;z<=5;z++){if((x+z)%4===0)continue;const h=.35+((x*x*7+z*z*11+42)%13)*.16,b=new THREE.Mesh(geo,material(colors[Math.abs(x+z)%6],.64));b.position.set(x*.55,h/2-1.8,z*.58);b.scale.y=h;root.add(b)}const ring=new THREE.Mesh(new THREE.TorusGeometry(3.6,.045,8,140),new THREE.MeshBasicMaterial({color:0xff6f91,transparent:true,opacity:.8}));ring.rotation.x=Math.PI/2;ring.position.y=-1.4;root.add(ring);root.rotation.y=-.48}
function globe(){const globe=new THREE.Mesh(new THREE.SphereGeometry(2.8,48,32),new THREE.MeshPhysicalMaterial({color:0x1a5272,transparent:true,opacity:.16,roughness:.15,transmission:.25,wireframe:false}));root.add(globe);const wire=new THREE.Mesh(new THREE.SphereGeometry(2.83,24,16),new THREE.MeshBasicMaterial({color:0x75b9d5,wireframe:true,transparent:true,opacity:.14}));root.add(wire);for(let i=0;i<18;i++){const a=i*2.399,y=-2.2+(i%9)*.55,r=Math.sqrt(Math.max(0,2.8**2-y**2)),p=new THREE.Vector3(Math.cos(a)*r,y,Math.sin(a)*r);const dot=new THREE.Mesh(new THREE.SphereGeometry(.09,12,8),material(colors[i%6],.95));dot.position.copy(p);root.add(dot);if(i>1){const q=root.children[root.children.length-3] as THREE.Mesh;const curve=new THREE.QuadraticBezierCurve3(q.position.clone(),q.position.clone().add(p).normalize().multiplyScalar(4),p);root.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(40)),new THREE.LineBasicMaterial({color:colors[i%6],transparent:true,opacity:.35})))}}root.rotation.y=-.5}
function ribbons(){for(let j=0;j<11;j++){const pts=Array.from({length:90},(_,i)=>new THREE.Vector3((i-45)*.095,Math.sin(i*.18+j*.7)*.55+(j-5)*.16,Math.cos(i*.12+j)*.8));const curve=new THREE.CatmullRomCurve3(pts),tube=new THREE.Mesh(new THREE.TubeGeometry(curve,180,.035+j%3*.012,8,false),material(colors[j%6],.62));root.add(tube)}root.rotation.set(.35,-.25,.12)}
function lattice(){const geo=new THREE.OctahedronGeometry(.12,0);for(let x=-4;x<=4;x++)for(let y=-3;y<=3;y++)for(let z=-2;z<=2;z++){if((x+y+z)%2)continue;const atom=new THREE.Mesh(geo,material(colors[(x*x+y*y+z*z)%6],.78));atom.position.set(x*.65,y*.65,z*.65);atom.scale.setScalar(1.4);root.add(atom)}const box=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(5.8,4.5,3.2)),new THREE.LineBasicMaterial({color:0x8ab5cc,transparent:true,opacity:.28}));root.add(box);root.rotation.set(.55,-.55,.18)}
function vectors(){const cone=new THREE.ConeGeometry(.08,.32,10);for(let x=-4;x<=4;x++)for(let y=-3;y<=3;y++)for(let z=-2;z<=2;z++){if((x+y+z)%2)continue;const v=new THREE.Vector3(-y*.18,x*.2,Math.sin((x+z)*.7)*.35),m=new THREE.Mesh(cone,material(colors[(x-y+12)%6],.72));m.position.set(x*.62,y*.62,z*.7);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());m.scale.y=.8+v.length();root.add(m)}root.rotation.set(.35,-.48,.08)}
function knots(){for(let j=0;j<5;j++){const knot=new THREE.Mesh(new THREE.TorusKnotGeometry(1.05+j*.18,.045+j*.008,220,10,2+j,3+j%2),material(colors[j],.66));knot.position.x=(j-2)*1.15;knot.rotation.set(j*.28,j*.42,j*.12);root.add(knot)}root.rotation.y=-.25}
function particles(){const count=12000,pos=new Float32Array(count*3),col=new Float32Array(count*3);for(let i=0;i<count;i++){const a=i*2.399,r=1.2+3.2*((i*37)%count)/count,phi=Math.acos(1-2*((i*53)%count)/count);pos[i*3]=Math.cos(a)*Math.sin(phi)*r;pos[i*3+1]=Math.cos(phi)*r;pos[i*3+2]=Math.sin(a)*Math.sin(phi)*r;const c=new THREE.Color(colors[i%6]);col.set([c.r,c.g,c.b],i*3)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));geo.setAttribute('color',new THREE.BufferAttribute(col,3));root.add(new THREE.Points(geo,new THREE.PointsMaterial({size:.055,vertexColors:true,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false})));root.rotation.y=-.4}
function metaballs(){for(let i=0;i<22;i++){const sphere=new THREE.Mesh(new THREE.SphereGeometry(.65+(i%5)*.11,32,20),new THREE.MeshPhysicalMaterial({color:colors[i%6],transparent:true,opacity:.18,roughness:.12,transmission:.35,thickness:.8,side:THREE.DoubleSide}));const a=i*2.399,r=.2+i*.12;sphere.position.set(Math.cos(a)*r,Math.sin(i*.8)*1.4,Math.sin(a)*r*.65);root.add(sphere)}const shell=new THREE.Mesh(new THREE.TorusKnotGeometry(2.1,.2,220,18,3,5),new THREE.MeshPhysicalMaterial({color:0x54d6c6,transparent:true,opacity:.25,roughness:.2,transmission:.4}));root.add(shell);root.rotation.set(.25,-.4,.15)}
const renderers:Record<string,()=>void>={orbital,terrain,crystal,molecule,city,globe,ribbons,lattice,vectors,knots,particles,metaballs};
(renderers[choice]??orbital)();
function render(){renderer.render(scene,camera)}controls.addEventListener('change',render);window.__INTERACTION_COUNT__=0;canvas.addEventListener('pointermove',()=>window.__INTERACTION_COUNT__=(window.__INTERACTION_COUNT__??0)+1);canvas.addEventListener('pointerdown',()=>window.__INTERACTION_COUNT__=(window.__INTERACTION_COUNT__??0)+1);render();requestAnimationFrame(()=>{render();window.__VIS_READY__=true});
